/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuideInstallationRouteImport } from './routes/guide/installation'
import { Route as CratesRokCliRouteImport } from './routes/crates/rok-cli'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideInstallationRoute = GuideInstallationRouteImport.update({
  id: '/guide/installation',
  path: '/guide/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const CratesRokCliRoute = CratesRokCliRouteImport.update({
  id: '/crates/rok-cli',
  path: '/crates/rok-cli',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/crates/rok-cli': typeof CratesRokCliRoute
  '/guide/installation': typeof GuideInstallationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/crates/rok-cli': typeof CratesRokCliRoute
  '/guide/installation': typeof GuideInstallationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/crates/rok-cli': typeof CratesRokCliRoute
  '/guide/installation': typeof GuideInstallationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/crates/rok-cli' | '/guide/installation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/crates/rok-cli' | '/guide/installation'
  id: '__root__' | '/' | '/about' | '/crates/rok-cli' | '/guide/installation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CratesRokCliRoute: typeof CratesRokCliRoute
  GuideInstallationRoute: typeof GuideInstallationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/installation': {
      id: '/guide/installation'
      path: '/guide/installation'
      fullPath: '/guide/installation'
      preLoaderRoute: typeof GuideInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crates/rok-cli': {
      id: '/crates/rok-cli'
      path: '/crates/rok-cli'
      fullPath: '/crates/rok-cli'
      preLoaderRoute: typeof CratesRokCliRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CratesRokCliRoute: CratesRokCliRoute,
  GuideInstallationRoute: GuideInstallationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
